name: "Vite Plugin Release"
on:
  push:
    branches: [bug/fix-ci-tests]

jobs:
  build_and_test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-dist
          retention-days: 1
          path: |
            packages/vite-plugin-posthog/dist
      - name: Create env file
        run: | 
          cd apps/example-react
          touch .env
          echo VITE_CHECK_FOR_DEV=false >> .env
          echo VITE_APP_TITLE=Example >> .env
          cat .env
          cd ../..

      # - name: "Build Vite App"
      #   run: npm run example:build
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps chromium
      # - name: Run Playwright tests
      #   run: npx playwright test
      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30