name: "Vite Plugin Release"
on:
  push:
    branches: [test/workflows]

jobs:
  version_check: 
    name: "Version Check"
    runs-on: "ubuntu-latest"
    steps: 
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0 # Necessary so we have commit history to compare to

        - name: Check vite-plugin-posthog version
          id: vpp_check
          uses: Octopus-Moneycoach/version-has-changed@v1
          with:
            path: packages/vite-plugin-posthog/package.json
            from: ${{github.event.before}}
            to: ${{github.event.after}}
    outputs: 
      vpp_changed: ${{ steps.vpp_check.outputs.changed}}


  main:
    name: "Main"
    needs: version_check
    if: needs.version_check.outputs.vpp_changed
    runs-on: ubuntu-latest
    steps:
        - name: "Task"
          run: echo "Has changed and is running"
